import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
若需修改请编辑 src/ 下的 TypeScript 源码
*/
`;

const prod = process.argv[2] === "production";

const options = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab",
    "@codemirror/commands", "@codemirror/language", "@codemirror/lint",
    "@codemirror/search", "@codemirror/state", "@codemirror/view",
    "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
};

if (prod) {
  // 生产：一次性构建后退出（可靠）。
  // 注：曾用 esbuild.context()+rebuild()，在本机 React 交付版上会挂起、
  // 导致 `npm run install` 的 build 步骤不退出、vault 不更新——已废弃该用法。
  await esbuild.build(options);
  process.exit(0);
} else {
  // 开发：监听模式
  const ctx = await esbuild.context(options);
  await ctx.watch();
}
